apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uievqqmup-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uievqqmup-go 
  name: uievqqmup-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: uievqqmup-go 
